//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/Empdata", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Employee : TestApp.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Emp_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NAmeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Emp_id {
            get {
                return this.Emp_idField;
            }
            set {
                if ((this.Emp_idField.Equals(value) != true)) {
                    this.Emp_idField = value;
                    this.RaisePropertyChanged("Emp_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NAme {
            get {
                return this.NAmeField;
            }
            set {
                if ((object.ReferenceEquals(this.NAmeField, value) != true)) {
                    this.NAmeField = value;
                    this.RaisePropertyChanged("NAme");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.ServiceReference1.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.ServiceReference1.City))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.ServiceReference1.Employee))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.ServiceReference1.City))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.ServiceReference1.Employee))]
    public partial class EntityObject : TestApp.ServiceReference1.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestApp.ServiceReference1.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestApp.ServiceReference1.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://schemas.datacontract.org/2004/07/Empdata", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class City : TestApp.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string City1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int City_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City1 {
            get {
                return this.City1Field;
            }
            set {
                if ((object.ReferenceEquals(this.City1Field, value) != true)) {
                    this.City1Field = value;
                    this.RaisePropertyChanged("City1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int City_id {
            get {
                return this.City_idField;
            }
            set {
                if ((this.City_idField.Equals(value) != true)) {
                    this.City_idField = value;
                    this.RaisePropertyChanged("City_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string District {
            get {
                return this.DistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictField, value) != true)) {
                    this.DistrictField = value;
                    this.RaisePropertyChanged("District");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestApp.ServiceReference1.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestApp.ServiceReference1.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.ServiceReference1.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.ServiceReference1.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.ServiceReference1.Employee[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.ServiceReference1.Employee))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.ServiceReference1.City[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.ServiceReference1.City))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.ServiceReference1.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.ServiceReference1.EntityKeyMember[]))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Empservice")]
    public interface Empservice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Empservice/GetEmployee", ReplyAction="http://tempuri.org/Empservice/GetEmployeeResponse")]
        TestApp.ServiceReference1.Employee[] GetEmployee();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Empservice/GetEmployee", ReplyAction="http://tempuri.org/Empservice/GetEmployeeResponse")]
        System.IAsyncResult BeginGetEmployee(System.AsyncCallback callback, object asyncState);
        
        TestApp.ServiceReference1.Employee[] EndGetEmployee(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Empservice/GetCity", ReplyAction="http://tempuri.org/Empservice/GetCityResponse")]
        TestApp.ServiceReference1.City[] GetCity();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Empservice/GetCity", ReplyAction="http://tempuri.org/Empservice/GetCityResponse")]
        System.IAsyncResult BeginGetCity(System.AsyncCallback callback, object asyncState);
        
        TestApp.ServiceReference1.City[] EndGetCity(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Empservice/save_employee", ReplyAction="http://tempuri.org/Empservice/save_employeeResponse")]
        bool save_employee(TestApp.ServiceReference1.Employee SaveObj);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Empservice/save_employee", ReplyAction="http://tempuri.org/Empservice/save_employeeResponse")]
        System.IAsyncResult Beginsave_employee(TestApp.ServiceReference1.Employee SaveObj, System.AsyncCallback callback, object asyncState);
        
        bool Endsave_employee(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Empservice/Save_city", ReplyAction="http://tempuri.org/Empservice/Save_cityResponse")]
        bool Save_city(TestApp.ServiceReference1.City CityObj);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Empservice/Save_city", ReplyAction="http://tempuri.org/Empservice/Save_cityResponse")]
        System.IAsyncResult BeginSave_city(TestApp.ServiceReference1.City CityObj, System.AsyncCallback callback, object asyncState);
        
        bool EndSave_city(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Empservice/Update_Employee", ReplyAction="http://tempuri.org/Empservice/Update_EmployeeResponse")]
        bool Update_Employee(TestApp.ServiceReference1.Employee UpdateObj);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Empservice/Update_Employee", ReplyAction="http://tempuri.org/Empservice/Update_EmployeeResponse")]
        System.IAsyncResult BeginUpdate_Employee(TestApp.ServiceReference1.Employee UpdateObj, System.AsyncCallback callback, object asyncState);
        
        bool EndUpdate_Employee(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmpserviceChannel : TestApp.ServiceReference1.Empservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TestApp.ServiceReference1.Employee[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TestApp.ServiceReference1.Employee[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TestApp.ServiceReference1.City[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TestApp.ServiceReference1.City[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class save_employeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public save_employeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Save_cityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Save_cityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Update_EmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Update_EmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpserviceClient : System.ServiceModel.ClientBase<TestApp.ServiceReference1.Empservice>, TestApp.ServiceReference1.Empservice {
        
        private BeginOperationDelegate onBeginGetEmployeeDelegate;
        
        private EndOperationDelegate onEndGetEmployeeDelegate;
        
        private System.Threading.SendOrPostCallback onGetEmployeeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCityDelegate;
        
        private EndOperationDelegate onEndGetCityDelegate;
        
        private System.Threading.SendOrPostCallback onGetCityCompletedDelegate;
        
        private BeginOperationDelegate onBeginsave_employeeDelegate;
        
        private EndOperationDelegate onEndsave_employeeDelegate;
        
        private System.Threading.SendOrPostCallback onsave_employeeCompletedDelegate;
        
        private BeginOperationDelegate onBeginSave_cityDelegate;
        
        private EndOperationDelegate onEndSave_cityDelegate;
        
        private System.Threading.SendOrPostCallback onSave_cityCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdate_EmployeeDelegate;
        
        private EndOperationDelegate onEndUpdate_EmployeeDelegate;
        
        private System.Threading.SendOrPostCallback onUpdate_EmployeeCompletedDelegate;
        
        public EmpserviceClient() {
        }
        
        public EmpserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetEmployeeCompletedEventArgs> GetEmployeeCompleted;
        
        public event System.EventHandler<GetCityCompletedEventArgs> GetCityCompleted;
        
        public event System.EventHandler<save_employeeCompletedEventArgs> save_employeeCompleted;
        
        public event System.EventHandler<Save_cityCompletedEventArgs> Save_cityCompleted;
        
        public event System.EventHandler<Update_EmployeeCompletedEventArgs> Update_EmployeeCompleted;
        
        public TestApp.ServiceReference1.Employee[] GetEmployee() {
            return base.Channel.GetEmployee();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetEmployee(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetEmployee(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TestApp.ServiceReference1.Employee[] EndGetEmployee(System.IAsyncResult result) {
            return base.Channel.EndGetEmployee(result);
        }
        
        private System.IAsyncResult OnBeginGetEmployee(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetEmployee(callback, asyncState);
        }
        
        private object[] OnEndGetEmployee(System.IAsyncResult result) {
            TestApp.ServiceReference1.Employee[] retVal = this.EndGetEmployee(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetEmployeeCompleted(object state) {
            if ((this.GetEmployeeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetEmployeeCompleted(this, new GetEmployeeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetEmployeeAsync() {
            this.GetEmployeeAsync(null);
        }
        
        public void GetEmployeeAsync(object userState) {
            if ((this.onBeginGetEmployeeDelegate == null)) {
                this.onBeginGetEmployeeDelegate = new BeginOperationDelegate(this.OnBeginGetEmployee);
            }
            if ((this.onEndGetEmployeeDelegate == null)) {
                this.onEndGetEmployeeDelegate = new EndOperationDelegate(this.OnEndGetEmployee);
            }
            if ((this.onGetEmployeeCompletedDelegate == null)) {
                this.onGetEmployeeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetEmployeeCompleted);
            }
            base.InvokeAsync(this.onBeginGetEmployeeDelegate, null, this.onEndGetEmployeeDelegate, this.onGetEmployeeCompletedDelegate, userState);
        }
        
        public TestApp.ServiceReference1.City[] GetCity() {
            return base.Channel.GetCity();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetCity(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCity(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TestApp.ServiceReference1.City[] EndGetCity(System.IAsyncResult result) {
            return base.Channel.EndGetCity(result);
        }
        
        private System.IAsyncResult OnBeginGetCity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetCity(callback, asyncState);
        }
        
        private object[] OnEndGetCity(System.IAsyncResult result) {
            TestApp.ServiceReference1.City[] retVal = this.EndGetCity(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCityCompleted(object state) {
            if ((this.GetCityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCityCompleted(this, new GetCityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCityAsync() {
            this.GetCityAsync(null);
        }
        
        public void GetCityAsync(object userState) {
            if ((this.onBeginGetCityDelegate == null)) {
                this.onBeginGetCityDelegate = new BeginOperationDelegate(this.OnBeginGetCity);
            }
            if ((this.onEndGetCityDelegate == null)) {
                this.onEndGetCityDelegate = new EndOperationDelegate(this.OnEndGetCity);
            }
            if ((this.onGetCityCompletedDelegate == null)) {
                this.onGetCityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCityCompleted);
            }
            base.InvokeAsync(this.onBeginGetCityDelegate, null, this.onEndGetCityDelegate, this.onGetCityCompletedDelegate, userState);
        }
        
        public bool save_employee(TestApp.ServiceReference1.Employee SaveObj) {
            return base.Channel.save_employee(SaveObj);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginsave_employee(TestApp.ServiceReference1.Employee SaveObj, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginsave_employee(SaveObj, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool Endsave_employee(System.IAsyncResult result) {
            return base.Channel.Endsave_employee(result);
        }
        
        private System.IAsyncResult OnBeginsave_employee(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TestApp.ServiceReference1.Employee SaveObj = ((TestApp.ServiceReference1.Employee)(inValues[0]));
            return this.Beginsave_employee(SaveObj, callback, asyncState);
        }
        
        private object[] OnEndsave_employee(System.IAsyncResult result) {
            bool retVal = this.Endsave_employee(result);
            return new object[] {
                    retVal};
        }
        
        private void Onsave_employeeCompleted(object state) {
            if ((this.save_employeeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.save_employeeCompleted(this, new save_employeeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void save_employeeAsync(TestApp.ServiceReference1.Employee SaveObj) {
            this.save_employeeAsync(SaveObj, null);
        }
        
        public void save_employeeAsync(TestApp.ServiceReference1.Employee SaveObj, object userState) {
            if ((this.onBeginsave_employeeDelegate == null)) {
                this.onBeginsave_employeeDelegate = new BeginOperationDelegate(this.OnBeginsave_employee);
            }
            if ((this.onEndsave_employeeDelegate == null)) {
                this.onEndsave_employeeDelegate = new EndOperationDelegate(this.OnEndsave_employee);
            }
            if ((this.onsave_employeeCompletedDelegate == null)) {
                this.onsave_employeeCompletedDelegate = new System.Threading.SendOrPostCallback(this.Onsave_employeeCompleted);
            }
            base.InvokeAsync(this.onBeginsave_employeeDelegate, new object[] {
                        SaveObj}, this.onEndsave_employeeDelegate, this.onsave_employeeCompletedDelegate, userState);
        }
        
        public bool Save_city(TestApp.ServiceReference1.City CityObj) {
            return base.Channel.Save_city(CityObj);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSave_city(TestApp.ServiceReference1.City CityObj, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSave_city(CityObj, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndSave_city(System.IAsyncResult result) {
            return base.Channel.EndSave_city(result);
        }
        
        private System.IAsyncResult OnBeginSave_city(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TestApp.ServiceReference1.City CityObj = ((TestApp.ServiceReference1.City)(inValues[0]));
            return this.BeginSave_city(CityObj, callback, asyncState);
        }
        
        private object[] OnEndSave_city(System.IAsyncResult result) {
            bool retVal = this.EndSave_city(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSave_cityCompleted(object state) {
            if ((this.Save_cityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Save_cityCompleted(this, new Save_cityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Save_cityAsync(TestApp.ServiceReference1.City CityObj) {
            this.Save_cityAsync(CityObj, null);
        }
        
        public void Save_cityAsync(TestApp.ServiceReference1.City CityObj, object userState) {
            if ((this.onBeginSave_cityDelegate == null)) {
                this.onBeginSave_cityDelegate = new BeginOperationDelegate(this.OnBeginSave_city);
            }
            if ((this.onEndSave_cityDelegate == null)) {
                this.onEndSave_cityDelegate = new EndOperationDelegate(this.OnEndSave_city);
            }
            if ((this.onSave_cityCompletedDelegate == null)) {
                this.onSave_cityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSave_cityCompleted);
            }
            base.InvokeAsync(this.onBeginSave_cityDelegate, new object[] {
                        CityObj}, this.onEndSave_cityDelegate, this.onSave_cityCompletedDelegate, userState);
        }
        
        public bool Update_Employee(TestApp.ServiceReference1.Employee UpdateObj) {
            return base.Channel.Update_Employee(UpdateObj);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUpdate_Employee(TestApp.ServiceReference1.Employee UpdateObj, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdate_Employee(UpdateObj, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndUpdate_Employee(System.IAsyncResult result) {
            return base.Channel.EndUpdate_Employee(result);
        }
        
        private System.IAsyncResult OnBeginUpdate_Employee(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TestApp.ServiceReference1.Employee UpdateObj = ((TestApp.ServiceReference1.Employee)(inValues[0]));
            return this.BeginUpdate_Employee(UpdateObj, callback, asyncState);
        }
        
        private object[] OnEndUpdate_Employee(System.IAsyncResult result) {
            bool retVal = this.EndUpdate_Employee(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdate_EmployeeCompleted(object state) {
            if ((this.Update_EmployeeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Update_EmployeeCompleted(this, new Update_EmployeeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Update_EmployeeAsync(TestApp.ServiceReference1.Employee UpdateObj) {
            this.Update_EmployeeAsync(UpdateObj, null);
        }
        
        public void Update_EmployeeAsync(TestApp.ServiceReference1.Employee UpdateObj, object userState) {
            if ((this.onBeginUpdate_EmployeeDelegate == null)) {
                this.onBeginUpdate_EmployeeDelegate = new BeginOperationDelegate(this.OnBeginUpdate_Employee);
            }
            if ((this.onEndUpdate_EmployeeDelegate == null)) {
                this.onEndUpdate_EmployeeDelegate = new EndOperationDelegate(this.OnEndUpdate_Employee);
            }
            if ((this.onUpdate_EmployeeCompletedDelegate == null)) {
                this.onUpdate_EmployeeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdate_EmployeeCompleted);
            }
            base.InvokeAsync(this.onBeginUpdate_EmployeeDelegate, new object[] {
                        UpdateObj}, this.onEndUpdate_EmployeeDelegate, this.onUpdate_EmployeeCompletedDelegate, userState);
        }
    }
}
